/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author SANTIAGO SIERRA
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeView
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCrudEmployee = new javax.swing.ButtonGroup();
        mainPane = new javax.swing.JPanel();
        entitySelectionPane = new javax.swing.JPanel();
        btnEmpPanel = new javax.swing.JButton();
        btnPasPanel = new javax.swing.JButton();
        btnLugPanel = new javax.swing.JButton();
        crudPane = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        dataDisplayPane = new javax.swing.JPanel();
        EmpPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEmployees = new javax.swing.JTable();
        textFieldEmployeeNumber = new javax.swing.JTextField();
        textFieldEmployeeName = new javax.swing.JTextField();
        labelEmpName = new javax.swing.JLabel();
        labelEmpNumber = new javax.swing.JLabel();
        btnSearchSelectEmp = new javax.swing.JButton();
        PasPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelPasID = new javax.swing.JLabel();
        txtFieldPassID = new javax.swing.JTextField();
        txtFieldPassName = new javax.swing.JTextField();
        labelPasName = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePassengers = new javax.swing.JTable();
        btnSearchSelectPas = new javax.swing.JButton();
        LugPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelLugID = new javax.swing.JLabel();
        txtFieldLugID = new javax.swing.JTextField();
        labelLugStatus = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableLuggage = new javax.swing.JTable();
        btnSearchSelectLug = new javax.swing.JButton();
        labelPasIDFkLug = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPane.setBackground(new java.awt.Color(204, 204, 204));

        entitySelectionPane.setBackground(new java.awt.Color(255, 255, 255));

        btnEmpPanel.setText("Employees");
        btnEmpPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpPanelActionPerformed(evt);
            }
        });

        btnPasPanel.setText("Passengers");
        btnPasPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasPanelActionPerformed(evt);
            }
        });

        btnLugPanel.setText("Luggage");
        btnLugPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLugPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entitySelectionPaneLayout = new javax.swing.GroupLayout(entitySelectionPane);
        entitySelectionPane.setLayout(entitySelectionPaneLayout);
        entitySelectionPaneLayout.setHorizontalGroup(
            entitySelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entitySelectionPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnPasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLugPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        entitySelectionPaneLayout.setVerticalGroup(
            entitySelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entitySelectionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entitySelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLugPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        crudPane.setBackground(new java.awt.Color(255, 255, 255));

        btnCreate.setText("Create");

        btnSearch.setText("Search");

        btnUpdate.setText("Update");

        btnDelete.setText("Delete");

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        btnGo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnGo.setText("GO!");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crudPaneLayout = new javax.swing.GroupLayout(crudPane);
        crudPane.setLayout(crudPaneLayout);
        crudPaneLayout.setHorizontalGroup(
            crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        crudPaneLayout.setVerticalGroup(
            crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataDisplayPane.setBackground(new java.awt.Color(255, 255, 255));
        dataDisplayPane.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel5.setText("Employees");

        tableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employee Number", "Employee Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableEmployees);

        textFieldEmployeeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeNumberActionPerformed(evt);
            }
        });

        textFieldEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeNameActionPerformed(evt);
            }
        });

        labelEmpName.setText("Employee Name");

        labelEmpNumber.setText("Employee Number");

        btnSearchSelectEmp.setText("Search/Select");
        btnSearchSelectEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSelectEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmpPaneLayout = new javax.swing.GroupLayout(EmpPane);
        EmpPane.setLayout(EmpPaneLayout);
        EmpPaneLayout.setHorizontalGroup(
            EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpPaneLayout.createSequentialGroup()
                        .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmpNumber)
                            .addComponent(labelEmpName))
                        .addGap(42, 42, 42)
                        .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EmpPaneLayout.createSequentialGroup()
                                .addComponent(textFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnSearchSelectEmp)))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpPaneLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(231, 231, 231))))
            .addGroup(EmpPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        EmpPaneLayout.setVerticalGroup(
            EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpPaneLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpNumber)
                    .addComponent(textFieldEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpName)
                    .addComponent(textFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSelectEmp))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        dataDisplayPane.add(EmpPane, "card2");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel6.setText("Passengers");

        labelPasID.setText("Passenger ID");

        txtFieldPassID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPassIDActionPerformed(evt);
            }
        });

        txtFieldPassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPassNameActionPerformed(evt);
            }
        });

        labelPasName.setText("Passenger Name");

        tablePassengers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Passenger ID", "Passanger Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablePassengers);

        btnSearchSelectPas.setText("Search/Select");

        javax.swing.GroupLayout PasPaneLayout = new javax.swing.GroupLayout(PasPane);
        PasPane.setLayout(PasPaneLayout);
        PasPaneLayout.setHorizontalGroup(
            PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasPaneLayout.createSequentialGroup()
                .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PasPaneLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PasPaneLayout.createSequentialGroup()
                                .addComponent(labelPasName)
                                .addGap(18, 18, 18)
                                .addComponent(txtFieldPassName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchSelectPas))
                            .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PasPaneLayout.createSequentialGroup()
                                    .addComponent(labelPasID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFieldPassID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PasPaneLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        PasPaneLayout.setVerticalGroup(
            PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasPaneLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addGap(40, 40, 40)
                .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasID)
                    .addComponent(txtFieldPassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldPassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSelectPas))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        dataDisplayPane.add(PasPane, "card2");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel7.setText("Luggage");

        labelLugID.setText("Luggage ID");

        txtFieldLugID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLugIDActionPerformed(evt);
            }
        });

        labelLugStatus.setText("Luggage Status");

        tableLuggage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Luggage ID", "Luggage Status", "Passenger ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableLuggage);

        btnSearchSelectLug.setText("Search/Select");

        labelPasIDFkLug.setText("Passenger ID");

        javax.swing.GroupLayout LugPaneLayout = new javax.swing.GroupLayout(LugPane);
        LugPane.setLayout(LugPaneLayout);
        LugPaneLayout.setHorizontalGroup(
            LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugPaneLayout.createSequentialGroup()
                .addGroup(LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugPaneLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPasIDFkLug)
                            .addComponent(labelLugStatus)
                            .addGroup(LugPaneLayout.createSequentialGroup()
                                .addComponent(labelLugID)
                                .addGap(122, 122, 122)
                                .addComponent(txtFieldLugID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchSelectLug))))
                    .addGroup(LugPaneLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel7))
                    .addGroup(LugPaneLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        LugPaneLayout.setVerticalGroup(
            LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugPaneLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addComponent(labelLugStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(labelPasIDFkLug)
                .addGap(43, 43, 43)
                .addGroup(LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLugID)
                    .addComponent(txtFieldLugID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchSelectLug))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        dataDisplayPane.add(LugPane, "card2");

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entitySelectionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addComponent(crudPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataDisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entitySelectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addComponent(dataDisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(crudPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
//        dataDisplayPane.removeAll();
//        dataDisplayPane.repaint();
//        dataDisplayPane.revalidate();
//        
//        dataDisplayPane.add(EmpPane);
//        dataDisplayPane.repaint();
//        dataDisplayPane.revalidate();
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnPasPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasPanelActionPerformed

    }//GEN-LAST:event_btnPasPanelActionPerformed

    private void btnEmpPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpPanelActionPerformed
        
    }//GEN-LAST:event_btnEmpPanelActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void textFieldEmployeeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeNumberActionPerformed

    private void textFieldEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeNameActionPerformed

    private void btnSearchSelectEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSelectEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSelectEmpActionPerformed

    private void txtFieldPassIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPassIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPassIDActionPerformed

    private void txtFieldPassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPassNameActionPerformed

    private void txtFieldLugIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLugIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldLugIDActionPerformed

    private void btnLugPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLugPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLugPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel EmpPane;
    public javax.swing.JPanel LugPane;
    public javax.swing.JPanel PasPane;
    public javax.swing.JButton btnClearFields;
    public javax.swing.JButton btnCreate;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnEmpPanel;
    public javax.swing.JButton btnGo;
    public javax.swing.ButtonGroup btnGroupCrudEmployee;
    public javax.swing.JButton btnLugPanel;
    public javax.swing.JButton btnPasPanel;
    public javax.swing.JButton btnSearch;
    public javax.swing.JButton btnSearchSelectEmp;
    public javax.swing.JButton btnSearchSelectLug;
    public javax.swing.JButton btnSearchSelectPas;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JPanel crudPane;
    public javax.swing.JPanel dataDisplayPane;
    private javax.swing.JPanel entitySelectionPane;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel labelEmpName;
    public javax.swing.JLabel labelEmpNumber;
    public javax.swing.JLabel labelLugID;
    public javax.swing.JLabel labelLugStatus;
    public javax.swing.JLabel labelPasID;
    public javax.swing.JLabel labelPasIDFkLug;
    public javax.swing.JLabel labelPasName;
    public javax.swing.JPanel mainPane;
    public javax.swing.JTable tableEmployees;
    public javax.swing.JTable tableLuggage;
    public javax.swing.JTable tablePassengers;
    public javax.swing.JTextField textFieldEmployeeName;
    public javax.swing.JTextField textFieldEmployeeNumber;
    public javax.swing.JTextField txtFieldLugID;
    public javax.swing.JTextField txtFieldPassID;
    public javax.swing.JTextField txtFieldPassName;
    // End of variables declaration//GEN-END:variables
}
