/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author SANTIAGO SIERRA
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeView
     */
    public MainFrame() {
        initComponents();
    }

    

    

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCrudEmployee = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mainPane = new javax.swing.JPanel();
        entitySelectionPane = new javax.swing.JPanel();
        btnEmpPanel = new javax.swing.JButton();
        btnPasPanel = new javax.swing.JButton();
        btnLugPanel = new javax.swing.JButton();
        btnBusPanel = new javax.swing.JButton();
        btnCitPanel = new javax.swing.JButton();
        btnTripPanel = new javax.swing.JButton();
        btnResPanel = new javax.swing.JButton();
        btnLookUpPanel = new javax.swing.JButton();
        crudPane = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClearFields = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        dataDisplayPane = new javax.swing.JPanel();
        EmpPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEmployees = new javax.swing.JTable();
        textFieldEmployeeNumber = new javax.swing.JTextField();
        textFieldEmployeeName = new javax.swing.JTextField();
        labelEmpName = new javax.swing.JLabel();
        labelEmpNumber = new javax.swing.JLabel();
        btnSearchSelectEmp = new javax.swing.JButton();
        PasPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelPasID = new javax.swing.JLabel();
        txtFieldPassID = new javax.swing.JTextField();
        txtFieldPassName = new javax.swing.JTextField();
        labelPasName = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePassengers = new javax.swing.JTable();
        btnSearchSelectPas = new javax.swing.JButton();
        LugPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelLugID = new javax.swing.JLabel();
        txtFieldLugID = new javax.swing.JTextField();
        labelLugStatus = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableLuggage = new javax.swing.JTable();
        btnSearchSelectLug = new javax.swing.JButton();
        labelPasIDFkLug = new javax.swing.JLabel();
        BusPane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableBuses = new javax.swing.JTable();
        textFieldBusID = new javax.swing.JTextField();
        labelBusSeatCap = new javax.swing.JLabel();
        labelBusID = new javax.swing.JLabel();
        btnSearchSelectBus = new javax.swing.JButton();
        CitPane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableCities = new javax.swing.JTable();
        textFieldCityName = new javax.swing.JTextField();
        labelCitName = new javax.swing.JLabel();
        btnSearchSelectCit = new javax.swing.JButton();
        TripPane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableTrips = new javax.swing.JTable();
        textFieldTripID = new javax.swing.JTextField();
        labelTripPrice = new javax.swing.JLabel();
        labelTripID = new javax.swing.JLabel();
        btnSearchSelectTrip = new javax.swing.JButton();
        labelTripDate = new javax.swing.JLabel();
        labelEmpNumFkTrip = new javax.swing.JLabel();
        labelBusIDFkTrip = new javax.swing.JLabel();
        labelOriCityFkTrip = new javax.swing.JLabel();
        labelDesCityFkTrip = new javax.swing.JLabel();
        DateChooserTripDate = new com.toedter.calendar.JDateChooser();
        textFieldTripsPrice = new javax.swing.JFormattedTextField();
        ResPane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tableReservations = new javax.swing.JTable();
        labelResNum = new javax.swing.JLabel();
        btnSearchSelectRes = new javax.swing.JButton();
        labelPassIDFkRes = new javax.swing.JLabel();
        labelTripIDFkRes = new javax.swing.JLabel();
        textFieldResNum = new javax.swing.JFormattedTextField();
        LookUpPane = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tableLookUp = new javax.swing.JTable();
        labelTripPriceLookUp = new javax.swing.JLabel();
        labelTripIDLookUp = new javax.swing.JLabel();
        btnSearchLookUp = new javax.swing.JButton();
        labelTripDateLookUp = new javax.swing.JLabel();
        labelEmpNumLookUp = new javax.swing.JLabel();
        labelBusIDLookUp = new javax.swing.JLabel();
        labelOriCityLookUp = new javax.swing.JLabel();
        labelDesCityLookUp = new javax.swing.JLabel();
        labelLugIDLookUp = new javax.swing.JLabel();
        labelLugStatusLookUp = new javax.swing.JLabel();
        labelEmpNameLookUp = new javax.swing.JLabel();
        labelPasIDLookUp = new javax.swing.JLabel();
        labelPasNameLookUp = new javax.swing.JLabel();
        labelSeatCapLookUp = new javax.swing.JLabel();
        btnResetLookUp = new javax.swing.JButton();
        labelResNumLookUp = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPane.setBackground(new java.awt.Color(204, 204, 204));

        entitySelectionPane.setBackground(new java.awt.Color(255, 255, 255));

        btnEmpPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpPanelActionPerformed(evt);
            }
        });

        btnPasPanel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnPasPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasPanelActionPerformed(evt);
            }
        });

        btnLugPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLugPanelActionPerformed(evt);
            }
        });

        btnBusPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusPanelActionPerformed(evt);
            }
        });

        btnCitPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitPanelActionPerformed(evt);
            }
        });

        btnTripPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTripPanelActionPerformed(evt);
            }
        });

        btnResPanel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnResPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResPanelActionPerformed(evt);
            }
        });

        btnLookUpPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookUpPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entitySelectionPaneLayout = new javax.swing.GroupLayout(entitySelectionPane);
        entitySelectionPane.setLayout(entitySelectionPaneLayout);
        entitySelectionPaneLayout.setHorizontalGroup(
            entitySelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entitySelectionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLugPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTripPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLookUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        entitySelectionPaneLayout.setVerticalGroup(
            entitySelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entitySelectionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entitySelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLugPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTripPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        crudPane.setBackground(new java.awt.Color(255, 255, 255));

        btnCreate.setText("Create");

        btnSearch.setText("Search");

        btnUpdate.setText("Update");

        btnDelete.setText("Delete");

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        btnGo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnGo.setText("GO!");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crudPaneLayout = new javax.swing.GroupLayout(crudPane);
        crudPane.setLayout(crudPaneLayout);
        crudPaneLayout.setHorizontalGroup(
            crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudPaneLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crudPaneLayout.setVerticalGroup(
            crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crudPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(crudPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(crudPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnClearFields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        dataDisplayPane.setBackground(new java.awt.Color(255, 255, 255));
        dataDisplayPane.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel5.setText("EMPLOYEES");

        tableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employee Number", "Employee Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableEmployees);

        textFieldEmployeeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeNumberActionPerformed(evt);
            }
        });

        textFieldEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmployeeNameActionPerformed(evt);
            }
        });

        labelEmpName.setText("Employee Name");

        labelEmpNumber.setText("Employee Number");

        btnSearchSelectEmp.setText("Search/Select");
        btnSearchSelectEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSelectEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmpPaneLayout = new javax.swing.GroupLayout(EmpPane);
        EmpPane.setLayout(EmpPaneLayout);
        EmpPaneLayout.setHorizontalGroup(
            EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpPaneLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 211, Short.MAX_VALUE))
            .addGroup(EmpPaneLayout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpPaneLayout.createSequentialGroup()
                        .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmpNumber)
                            .addComponent(labelEmpName))
                        .addGap(42, 42, 42)
                        .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpPaneLayout.createSequentialGroup()
                        .addComponent(btnSearchSelectEmp)
                        .addGap(85, 85, 85)))
                .addGap(349, 349, 349))
        );
        EmpPaneLayout.setVerticalGroup(
            EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpPaneLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpNumber)
                    .addComponent(textFieldEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EmpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpName)
                    .addComponent(textFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnSearchSelectEmp)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        dataDisplayPane.add(EmpPane, "card2");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel6.setText("PASSENGERS");

        labelPasID.setText("Passenger ID");

        txtFieldPassID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPassIDActionPerformed(evt);
            }
        });

        txtFieldPassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPassNameActionPerformed(evt);
            }
        });

        labelPasName.setText("Passenger Name");

        tablePassengers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Passenger ID", "Passanger Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablePassengers);

        btnSearchSelectPas.setText("Search/Select");

        javax.swing.GroupLayout PasPaneLayout = new javax.swing.GroupLayout(PasPane);
        PasPane.setLayout(PasPaneLayout);
        PasPaneLayout.setHorizontalGroup(
            PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasPaneLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasPaneLayout.createSequentialGroup()
                        .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PasPaneLayout.createSequentialGroup()
                                    .addComponent(labelPasName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFieldPassName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PasPaneLayout.createSequentialGroup()
                                    .addComponent(labelPasID)
                                    .addGap(33, 33, 33)
                                    .addComponent(txtFieldPassID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasPaneLayout.createSequentialGroup()
                        .addComponent(btnSearchSelectPas)
                        .addGap(443, 443, 443))))
        );
        PasPaneLayout.setVerticalGroup(
            PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasID)
                    .addComponent(txtFieldPassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldPassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnSearchSelectPas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        dataDisplayPane.add(PasPane, "card2");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel7.setText("LUGGAGE");

        labelLugID.setText("Luggage ID");

        txtFieldLugID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldLugIDActionPerformed(evt);
            }
        });

        labelLugStatus.setText("Luggage Status");

        tableLuggage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Luggage ID", "Luggage Status", "Passenger ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableLuggage);

        btnSearchSelectLug.setText("Search/Select");

        labelPasIDFkLug.setText("Passenger ID");

        javax.swing.GroupLayout LugPaneLayout = new javax.swing.GroupLayout(LugPane);
        LugPane.setLayout(LugPaneLayout);
        LugPaneLayout.setHorizontalGroup(
            LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LugPaneLayout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addGroup(LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LugPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LugPaneLayout.createSequentialGroup()
                        .addComponent(btnSearchSelectLug)
                        .addGap(445, 445, 445))))
            .addGroup(LugPaneLayout.createSequentialGroup()
                .addGroup(LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LugPaneLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel7))
                    .addGroup(LugPaneLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addGroup(LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPasIDFkLug)
                            .addComponent(labelLugStatus)
                            .addGroup(LugPaneLayout.createSequentialGroup()
                                .addComponent(labelLugID)
                                .addGap(66, 66, 66)
                                .addComponent(txtFieldLugID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LugPaneLayout.setVerticalGroup(
            LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LugPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(LugPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLugID)
                    .addComponent(txtFieldLugID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(labelLugStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(labelPasIDFkLug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnSearchSelectLug)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        dataDisplayPane.add(LugPane, "card2");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel8.setText("BUSES");

        tableBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Bus ID", "Sear Capacity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableBuses);

        textFieldBusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBusIDActionPerformed(evt);
            }
        });

        labelBusSeatCap.setText("Seat Capacity");

        labelBusID.setText("Bus ID");

        btnSearchSelectBus.setText("Search/Select");
        btnSearchSelectBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSelectBusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BusPaneLayout = new javax.swing.GroupLayout(BusPane);
        BusPane.setLayout(BusPaneLayout);
        BusPaneLayout.setHorizontalGroup(
            BusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusPaneLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(labelBusSeatCap)
                .addGap(154, 154, 154)
                .addComponent(labelBusID)
                .addGap(34, 34, 34)
                .addComponent(textFieldBusID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusPaneLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(BusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusPaneLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(426, 426, 426))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusPaneLayout.createSequentialGroup()
                        .addComponent(btnSearchSelectBus)
                        .addGap(429, 429, 429))))
        );
        BusPaneLayout.setVerticalGroup(
            BusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(41, 41, 41)
                .addGroup(BusPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBusID)
                    .addComponent(textFieldBusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBusSeatCap))
                .addGap(49, 49, 49)
                .addComponent(btnSearchSelectBus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        dataDisplayPane.add(BusPane, "card2");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel9.setText("CITIES");

        tableCities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "City Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableCities);

        textFieldCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCityNameActionPerformed(evt);
            }
        });

        labelCitName.setText("City Name");

        btnSearchSelectCit.setText("Search/Select");
        btnSearchSelectCit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSelectCitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CitPaneLayout = new javax.swing.GroupLayout(CitPane);
        CitPane.setLayout(CitPaneLayout);
        CitPaneLayout.setHorizontalGroup(
            CitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CitPaneLayout.createSequentialGroup()
                .addGroup(CitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CitPaneLayout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(labelCitName)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CitPaneLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(btnSearchSelectCit))
                    .addGroup(CitPaneLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CitPaneLayout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jLabel9)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        CitPaneLayout.setVerticalGroup(
            CitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CitPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(CitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCitName)
                    .addComponent(textFieldCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnSearchSelectCit)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        dataDisplayPane.add(CitPane, "card2");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel10.setText("TRIPS");

        tableTrips.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Trip ID", "Trip Date", "Price", "Origin City", "Destiny City", "Emp Number", "Bus ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tableTrips);

        textFieldTripID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTripIDActionPerformed(evt);
            }
        });

        labelTripPrice.setText("Price");

        labelTripID.setText("Trip ID");

        btnSearchSelectTrip.setText("Search/Select");
        btnSearchSelectTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSelectTripActionPerformed(evt);
            }
        });

        labelTripDate.setText("Trip Date");

        labelEmpNumFkTrip.setText("Employee Number");

        labelBusIDFkTrip.setText("Bus ID");

        labelOriCityFkTrip.setText("Origin City");

        labelDesCityFkTrip.setText("Destiny City");

        textFieldTripsPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));

        javax.swing.GroupLayout TripPaneLayout = new javax.swing.GroupLayout(TripPane);
        TripPane.setLayout(TripPaneLayout);
        TripPaneLayout.setHorizontalGroup(
            TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TripPaneLayout.createSequentialGroup()
                .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TripPaneLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTripID)
                            .addComponent(labelTripPrice)
                            .addComponent(labelTripDate))
                        .addGap(41, 41, 41)
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTripID, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateChooserTripDate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTripsPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153)
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOriCityFkTrip)
                            .addComponent(labelDesCityFkTrip)
                            .addComponent(labelBusIDFkTrip)
                            .addComponent(labelEmpNumFkTrip)))
                    .addGroup(TripPaneLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchSelectTrip))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TripPaneLayout.createSequentialGroup()
                .addGap(0, 143, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        TripPaneLayout.setVerticalGroup(
            TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TripPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TripPaneLayout.createSequentialGroup()
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTripID)
                            .addComponent(textFieldTripID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateChooserTripDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTripDate))
                        .addGap(18, 18, 18)
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTripPrice)
                            .addComponent(textFieldTripsPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TripPaneLayout.createSequentialGroup()
                        .addGroup(TripPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOriCityFkTrip)
                            .addGroup(TripPaneLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(labelDesCityFkTrip)))
                        .addGap(21, 21, 21)
                        .addComponent(labelEmpNumFkTrip)
                        .addGap(18, 18, 18)
                        .addComponent(labelBusIDFkTrip)))
                .addGap(30, 30, 30)
                .addComponent(btnSearchSelectTrip)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        dataDisplayPane.add(TripPane, "card2");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel11.setText("RESERVATIONS");

        tableReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Reservation Num", "Passenger ID", "Trip ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tableReservations);

        labelResNum.setText("Reservation Number");

        btnSearchSelectRes.setText("Search/Select");
        btnSearchSelectRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSelectResActionPerformed(evt);
            }
        });

        labelPassIDFkRes.setText("Passenger ID");

        labelTripIDFkRes.setText("Trip ID");

        textFieldResNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0"))));
        textFieldResNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldResNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResPaneLayout = new javax.swing.GroupLayout(ResPane);
        ResPane.setLayout(ResPaneLayout);
        ResPaneLayout.setHorizontalGroup(
            ResPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResPaneLayout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(ResPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPassIDFkRes)
                    .addComponent(labelTripIDFkRes)
                    .addGroup(ResPaneLayout.createSequentialGroup()
                        .addComponent(labelResNum)
                        .addGap(34, 34, 34)
                        .addComponent(textFieldResNum, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResPaneLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnSearchSelectRes)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ResPaneLayout.createSequentialGroup()
                .addGroup(ResPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResPaneLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel11))
                    .addGroup(ResPaneLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        ResPaneLayout.setVerticalGroup(
            ResPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addGap(39, 39, 39)
                .addComponent(labelPassIDFkRes)
                .addGap(18, 18, 18)
                .addComponent(labelTripIDFkRes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(ResPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResNum)
                    .addComponent(textFieldResNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSearchSelectRes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        dataDisplayPane.add(ResPane, "card2");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel12.setText("LOOK UP");

        tableLookUp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Trip ID", "Trip Date", "Origin City", "Destiny City", "Price", "Emp Number", "Emp Name", "Res Num", "Bus ID", "Lug ID", "Lug Status", "Pass ID", "Pass Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tableLookUp);

        labelTripPriceLookUp.setText("Price");

        labelTripIDLookUp.setText("Trip ID");

        btnSearchLookUp.setText("Search");
        btnSearchLookUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLookUpActionPerformed(evt);
            }
        });

        labelTripDateLookUp.setText("Trip Date");

        labelEmpNumLookUp.setText("Employee Number");

        labelBusIDLookUp.setText("Bus ID");

        labelOriCityLookUp.setText("Origin City");

        labelDesCityLookUp.setText("Destiny City");

        labelLugIDLookUp.setText("Luggage ID");

        labelLugStatusLookUp.setText("Luggage Status");

        labelEmpNameLookUp.setText("Employee Name");

        labelPasIDLookUp.setText("Passenger ID");

        labelPasNameLookUp.setText("Passenger Name");

        labelSeatCapLookUp.setText("Seat Capacity");

        btnResetLookUp.setText("Reset");
        btnResetLookUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetLookUpActionPerformed(evt);
            }
        });

        labelResNumLookUp.setText("Reservation Num");

        javax.swing.GroupLayout LookUpPaneLayout = new javax.swing.GroupLayout(LookUpPane);
        LookUpPane.setLayout(LookUpPaneLayout);
        LookUpPaneLayout.setHorizontalGroup(
            LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LookUpPaneLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTripDateLookUp)
                    .addComponent(labelDesCityLookUp)
                    .addComponent(labelOriCityLookUp)
                    .addComponent(labelTripIDLookUp))
                .addGap(118, 118, 118)
                .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LookUpPaneLayout.createSequentialGroup()
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTripPriceLookUp)
                            .addComponent(labelResNumLookUp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLugIDLookUp)
                            .addComponent(labelBusIDLookUp)
                            .addComponent(labelLugStatusLookUp))
                        .addGap(144, 144, 144)
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPasIDLookUp)
                            .addComponent(labelSeatCapLookUp)
                            .addComponent(labelPasNameLookUp))
                        .addGap(167, 167, 167))
                    .addGroup(LookUpPaneLayout.createSequentialGroup()
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmpNumLookUp)
                            .addComponent(labelEmpNameLookUp))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPaneLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPaneLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(425, 425, 425))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(LookUpPaneLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(btnSearchLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnResetLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LookUpPaneLayout.setVerticalGroup(
            LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LookUpPaneLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(17, 17, 17)
                .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LookUpPaneLayout.createSequentialGroup()
                        .addComponent(labelBusIDLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(labelLugIDLookUp)
                        .addGap(37, 37, 37)
                        .addComponent(labelLugStatusLookUp))
                    .addGroup(LookUpPaneLayout.createSequentialGroup()
                        .addComponent(labelSeatCapLookUp)
                        .addGap(29, 29, 29)
                        .addComponent(labelPasIDLookUp)
                        .addGap(37, 37, 37)
                        .addComponent(labelPasNameLookUp))
                    .addGroup(LookUpPaneLayout.createSequentialGroup()
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTripIDLookUp)
                            .addComponent(labelTripPriceLookUp))
                        .addGap(19, 19, 19)
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTripDateLookUp)
                            .addComponent(labelEmpNumLookUp))
                        .addGap(18, 18, 18)
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelOriCityLookUp)
                            .addComponent(labelEmpNameLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDesCityLookUp)
                            .addComponent(labelResNumLookUp))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(LookUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchLookUp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        dataDisplayPane.add(LookUpPane, "card2");

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataDisplayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entitySelectionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crudPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entitySelectionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crudPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataDisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
//        dataDisplayPane.removeAll();
//        dataDisplayPane.repaint();
//        dataDisplayPane.revalidate();
//        
//        dataDisplayPane.add(EmpPane);
//        dataDisplayPane.repaint();
//        dataDisplayPane.revalidate();
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnPasPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasPanelActionPerformed

    }//GEN-LAST:event_btnPasPanelActionPerformed

    private void btnEmpPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpPanelActionPerformed
        
    }//GEN-LAST:event_btnEmpPanelActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void textFieldEmployeeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeNumberActionPerformed

    private void textFieldEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmployeeNameActionPerformed

    private void btnSearchSelectEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSelectEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSelectEmpActionPerformed

    private void txtFieldPassIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPassIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPassIDActionPerformed

    private void txtFieldPassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPassNameActionPerformed

    private void txtFieldLugIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldLugIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldLugIDActionPerformed

    private void btnLugPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLugPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLugPanelActionPerformed

    private void textFieldBusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBusIDActionPerformed

    private void btnSearchSelectBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSelectBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSelectBusActionPerformed

    private void btnBusPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusPanelActionPerformed

    private void textFieldCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCityNameActionPerformed

    private void btnSearchSelectCitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSelectCitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSelectCitActionPerformed

    private void btnCitPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitPanelActionPerformed

    private void textFieldTripIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTripIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTripIDActionPerformed

    private void btnSearchSelectTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSelectTripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSelectTripActionPerformed

    private void btnTripPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTripPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTripPanelActionPerformed

    private void btnSearchSelectResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSelectResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchSelectResActionPerformed

    private void btnResPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResPanelActionPerformed

    private void btnSearchLookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLookUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchLookUpActionPerformed

    private void btnResetLookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetLookUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetLookUpActionPerformed

    private void btnLookUpPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookUpPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLookUpPanelActionPerformed

    private void textFieldResNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldResNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldResNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BusPane;
    public javax.swing.JPanel CitPane;
    public com.toedter.calendar.JDateChooser DateChooserTripDate;
    public javax.swing.JPanel EmpPane;
    public javax.swing.JPanel LookUpPane;
    public javax.swing.JPanel LugPane;
    public javax.swing.JPanel PasPane;
    public javax.swing.JPanel ResPane;
    public javax.swing.JPanel TripPane;
    public javax.swing.JButton btnBusPanel;
    public javax.swing.JButton btnCitPanel;
    public javax.swing.JButton btnClearFields;
    public javax.swing.JButton btnCreate;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnEmpPanel;
    public javax.swing.JButton btnGo;
    public javax.swing.ButtonGroup btnGroupCrudEmployee;
    public javax.swing.JButton btnLookUpPanel;
    public javax.swing.JButton btnLugPanel;
    public javax.swing.JButton btnPasPanel;
    public javax.swing.JButton btnResPanel;
    public javax.swing.JButton btnResetLookUp;
    public javax.swing.JButton btnSearch;
    public javax.swing.JButton btnSearchLookUp;
    public javax.swing.JButton btnSearchSelectBus;
    public javax.swing.JButton btnSearchSelectCit;
    public javax.swing.JButton btnSearchSelectEmp;
    public javax.swing.JButton btnSearchSelectLug;
    public javax.swing.JButton btnSearchSelectPas;
    public javax.swing.JButton btnSearchSelectRes;
    public javax.swing.JButton btnSearchSelectTrip;
    public javax.swing.JButton btnTripPanel;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JPanel crudPane;
    public javax.swing.JPanel dataDisplayPane;
    private javax.swing.JPanel entitySelectionPane;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel labelBusID;
    public javax.swing.JLabel labelBusIDFkTrip;
    public javax.swing.JLabel labelBusIDLookUp;
    public javax.swing.JLabel labelBusSeatCap;
    public javax.swing.JLabel labelCitName;
    public javax.swing.JLabel labelDesCityFkTrip;
    public javax.swing.JLabel labelDesCityLookUp;
    public javax.swing.JLabel labelEmpName;
    private javax.swing.JLabel labelEmpNameLookUp;
    public javax.swing.JLabel labelEmpNumFkTrip;
    public javax.swing.JLabel labelEmpNumLookUp;
    public javax.swing.JLabel labelEmpNumber;
    public javax.swing.JLabel labelLugID;
    private javax.swing.JLabel labelLugIDLookUp;
    public javax.swing.JLabel labelLugStatus;
    private javax.swing.JLabel labelLugStatusLookUp;
    public javax.swing.JLabel labelOriCityFkTrip;
    public javax.swing.JLabel labelOriCityLookUp;
    public javax.swing.JLabel labelPasID;
    public javax.swing.JLabel labelPasIDFkLug;
    private javax.swing.JLabel labelPasIDLookUp;
    public javax.swing.JLabel labelPasName;
    private javax.swing.JLabel labelPasNameLookUp;
    public javax.swing.JLabel labelPassIDFkRes;
    public javax.swing.JLabel labelResNum;
    private javax.swing.JLabel labelResNumLookUp;
    private javax.swing.JLabel labelSeatCapLookUp;
    public javax.swing.JLabel labelTripDate;
    public javax.swing.JLabel labelTripDateLookUp;
    public javax.swing.JLabel labelTripID;
    public javax.swing.JLabel labelTripIDFkRes;
    public javax.swing.JLabel labelTripIDLookUp;
    public javax.swing.JLabel labelTripPrice;
    public javax.swing.JLabel labelTripPriceLookUp;
    public javax.swing.JPanel mainPane;
    public javax.swing.JTable tableBuses;
    public javax.swing.JTable tableCities;
    public javax.swing.JTable tableEmployees;
    public javax.swing.JTable tableLookUp;
    public javax.swing.JTable tableLuggage;
    public javax.swing.JTable tablePassengers;
    public javax.swing.JTable tableReservations;
    public javax.swing.JTable tableTrips;
    public javax.swing.JTextField textFieldBusID;
    public javax.swing.JTextField textFieldCityName;
    public javax.swing.JTextField textFieldEmployeeName;
    public javax.swing.JTextField textFieldEmployeeNumber;
    public javax.swing.JFormattedTextField textFieldResNum;
    public javax.swing.JTextField textFieldTripID;
    public javax.swing.JFormattedTextField textFieldTripsPrice;
    public javax.swing.JTextField txtFieldLugID;
    public javax.swing.JTextField txtFieldPassID;
    public javax.swing.JTextField txtFieldPassName;
    // End of variables declaration//GEN-END:variables
}


